const OOF_TXT = {
  T0: 'Out of filament on T0',
  T1: 'Out of filament on T1'
}
const INDUCTIVE_SENSOR_RANGE = 32736
const BED_TEMP_WARNING_THRESHOLD = 120
const BUILD_CHAMBER_TEMP_WARNING_THRESHOLD = 60
const FILAMENT_CHAMBER_TEMP_WARNING_THRESHOLD = 60
const EXTRUDER_TEMP_WARNING_THRESHOLD = 280

export {
  OOF_TXT,
  INDUCTIVE_SENSOR_RANGE,
  BED_TEMP_WARNING_THRESHOLD,
  BUILD_CHAMBER_TEMP_WARNING_THRESHOLD,
  FILAMENT_CHAMBER_TEMP_WARNING_THRESHOLD,
  EXTRUDER_TEMP_WARNING_THRESHOLD
}
