import enum


class PrinterState(enum.Enum):
    NC_PROGRAM_IS_RUNNING = 0
    HEATING_UP_IN_PROGRESS = 1
    COOLING_DOWN_IN_PROGRESS = 2
    MANUAL_OPERATION_MODE = 3
    WAITING_FOR_USER_ACTION = 4
    JOB_FINISHED = 5
    HEATING_UP_FINISHED = 6
    COOLING_DOWN_FINISHED = 7
    T0_IS_OUT_OF_FILAMENT = 8
    AT_LEAST_ONE_DOOR_IS_OPEN = 9
    E_STOP_HAS_BEEN_TRIGGERED = 10
    CHANNEL_ERROR = 11
    EXCEEDING_TEMPERATURE_LIMITS = 12
    JOB_IS_RUNNING = 13
    PRINTER_IS_IDLE = 14
    TEMPERATURE_MODULE_ERROR = 15
    HEATING_CONTROL_ERROR = 16
    TEMPERATURE_SYSTEM_DATA_ERROR = 17
    AXIS_IN_ERROR_STATE = 18
    SAFETY_ERROR = 19
    DOORS_NOT_LOCKED = 20
    T1_IS_OUT_OF_FILAMENT = 21
    # Please keep NUM_STATES up to date if you add states.
    # It should always come last and be equal to the number of states.
    NUM_STATES = 22
